# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8.0에 맞는 드라이버 클래스
    url: jdbc:mysql://dddb.c3iucig8edyl.ap-northeast-2.rds.amazonaws.com:3306/dddb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 #${SPRING_DATASOURCE_URL} # database 이름
    username: root
    password: 403595sh #${SPRING_DATASOURCE_PASSWORD}

  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update


  mvc:
    contentnegotiation:
      media-types:
        json: application/json
      default-media-type: application/json
