spring.application.name=server
SPRING_DATASORCE_URL = jdbc:mysql://127.0.0.1:3306/dddb
SPRING_DATASOURCE_PASSWORD = 403595
root@127.0.0.1:3306
jdbc:mysql://127.0.0.1:3306/?user=root
spring.jwt.secret=af86bed1b346575a174c4026addb078151bd2484be48655c69bb8155f7d3c1f3cafd0bf5f2dab7ad665ce4f9e42df366d421a9dc041d78e377fab127d237b988
#?? smtp ?? (????)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#???? ??? ????(??? ??? ??)
spring.mail.username=docdi2024@gmail.com
spring.mail.password=hiol trtk uouc hdqe
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true
